### ISSUE TITLE
Social buttons stack badly on mobile and tablet

### ISSUE THREAD

**Issue by aikijambo** [aikido-gi-yu-jin/aikido-gi-yu-jin.github.io#27]
Just spotted that the facebook and twitter buttons on the home page at out of line.
![wp_ss_20150606_0001](https://cloud.githubusercontent.com/assets/11269542/8020897/2535bf3e-0c82-11e5-97e7-4679f10c4cd5.png)

**Comment by mowat27** [comment]
Opps, my bad.  This affects the tablet and phone viewports.  Renaming the issue accordingly
