### ISSUE TITLE
Show Google Map

### ISSUE THREAD

**Issue by mowat27** [aikido-gi-yu-jin/aikido-gi-yu-jin.github.io#5]
As a user, I want to be able to see bellahouston sports centre on a map

**Comment by aikijambo** [comment]
As a mobile user I don't want the map taking up my whole screen. This prevents scrolling!

**Comment by mowat27** [comment]
@aikijambo I added a couple of examples at http://aikido-gi-yu-jin.github.io/playpen.html

I take it the interactive map at the top demonstrates the problem with scrolling on touch devices?  The static map example doesn't have that problem but it's not interactive so it's less useful.

**Comment by aikijambo** [comment]
The interactive map works perfect as is because there is space to place fingers for scrolling. Was meaning if the map was too large in relation to screen size

**Comment by mowat27** [comment]
Hmm, still not ideal  One way we could deal with this is put the image in on small touch devices and make it clickable so the map opens in a small tab.  We'd still show the fully interactive map on tablets and desktops.

**Comment by aikijambo** [comment]
So on a phone, for example, the map would appear as a still image until clicked, where it would then be interactive? Or a small still image that, when clicked, would open out into a larger still?

**Comment by mowat27** [comment]
Google map is linked from the main site in a452f0b
