### ISSUE TITLE
Improve Design

### ISSUE THREAD

**Issue by mowat27** [aikido-gi-yu-jin/aikido-gi-yu-jin.github.io#8]
As a website admin I would like someone to create a design for this site.

* It must use a framework like [bootstrap](http://getbootstrap.com/) so we can apply it easily
* The artefacts and colour scheme must be easy to port to the Twitter and Facebook pages

**Comment by mowat27** [comment]
A couple of out of the box templates we could use...

http://getbootstrap.com/examples/carousel
http://getbootstrap.com/examples/cover/

**Comment by aikijambo** [comment]
Carousel is nice can you post a link/steps to locating more templates?

**Comment by mowat27** [comment]
I thought so too

If you just google Bootstrap Templates there are plenty to choose from but you have to pay for a lot of the good ones.

I suggest we start with a basic one and see if we can call in a favour from a web designer to roll us something unique.

I, or someone with dev skills, will need to apply the template initially. It's not just a case of clicking a button

**Comment by mowat27** [comment]
I'm working on adding the bootstrap carousel at the moment.  I'll push it up when it's presentable and add instructions to the README as per #11

**Comment by mowat27** [comment]
Applied design based on bootstrap carousel in a452f0b
